name: utkarsh_aichatbot
description: "An AI chatbot for multipurpose activities,using chatgpt api developed by utkarsh."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
#hive database
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  #for accessing storage path
  path_provider: ^2.1.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  get: ^4.6.6
  flutter_animate: ^4.5.0
  http: ^1.2.1
  flutter_gemini: ^2.0.4
  dash_chat_2: ^0.0.21
  image_picker: ^1.1.2
  brain_fusion: ^0.1.1
  provider: ^6.1.2
  google_fonts: ^6.2.1

 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
   
   # - images/a_dot_ham.jp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
